### PR TITLE
Add required header, fix printf and return

### PR DESCRIPTION
**Pull request by ClashLuke**

### CODE REVIEW

**Comment by yusufavianto** [comment]
hello
i had try the code on my honor 10 lite (HRY-AL00a) with emui 9.1.0.291
but failed
should i downgrade to emui 9 to make the code work ?

**Comment by ClashLuke** [comment]
It takes a while to bruteforce the code. Considering there are about 10^16 different codes and each try takes about 20ms, you need up to 634195 years to find the right code. On average it'd be half that.

**Comment by CodENooBUseR** [comment]
do you mean it's almost impossible ?

**Comment by CodENooBUseR** [comment]
ok i got it
thank you Mr.ClashLuke

**Comment by Martazza** [comment]
Thank you for your contribution!

**Comment by Maicol86** [comment]
help

**Comment by Abilash-22** [comment]
I understand it's closed but what do you see on terminal once you run "./exec" ? Because I see
"sh: 1: fastboot: not found"
it would have been helpful to have some sample logs.

**Comment by Abilash-22** [comment]
I understand it's closed but what do you see on terminal once you run "./exec" ? Because I see
"sh: 1: fastboot: not found"
it would have been helpful to have some sample logs.

**Pull request merged**
