### PR TITLE
Automatically build with GitHub Actions

### PR DESCRIPTION
**Pull request by Minionguyjpro**
I've made some changes it will be able to make a build after every push on GitHub. Just download the generated artifact containting the executable file.

### CODE REVIEW

**Comment by Abilash-22** [comment]
Hey Minion,
This program is suppposed to check 10^16 unlock codes for each device, what if I have a file which contains only 300k unlock codes and want to only check them?
is there a possibility to modify the program to input file in order to reduce the time taken to find out the unlock code?

**Comment by Minionguyjpro** [comment]
> Hey Minion, This program is suppposed to check 10^16 unlock codes for each device, what if I have a file which contains only 300k unlock codes and want to check only them? Is there a possibility to modify the program to read input file in order to reduce the time taken to find the unlock code?

Hello,

That might be possible, but don't know how to do it. Maybe with some research.

**Comment by MartinBraquet** [comment]
@Abilash-22 I'm trying to crack my Huawei's code but it would take millennia with 10^16 codes. Do you happen to know if the set of Huawei codes is restricted to those 300k codes you mentioned? If yes, may I have access to them? Thanks!

**Comment by Abilash-22** [comment]
> @Abilash-22 I'm trying to crack my Huawei's code but it would take millennia with 10^16 codes. Do you happen to know if the set of Huawei codes is restricted to those 300k codes you mentioned? If yes, may I have access to them? Thanks!

Unfortunately no, mate. The devices which run on Android 8 or before can be unlocked using those 300k codes.
But Android 9 or after requires alphanumeric codes to unlock and that is impossible 😭. I gave it up and decided not to buy Huawei anymore.

**Comment by Abilash-22** [comment]
> @Abilash-22 Lol okay... I have a Huawei P8 Lite with Android 5 or 6 (https://www.gsmarena.com/huawei_p8lite-7201.php). So it should work with those codes hopefully. If you have or know where to get those codes, that would help me a ton! If you need to DM: `martin.braquet [at] hotmail [dot] com`

I think this one, follow the instructions - https://xdaforums.com/t/huawei-bootloader-brute-force.4151859/
Basically the script will try to unlock your device using some 300k codes, if your device gets unlocked on the 5th code not the 300kth code consider yourself lucky. If it doesn't then very unlucky.

Script will create a .txt file containing all the codes which were tested and you can refer it.

**Pull request merged**
